# -*- coding: utf-8 -*-
"""QM2 Embedding Graph

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/jeanne12345/18bfd33dd41fe784f4f61f6e5d1b8d90/qm2-embedding-graph.ipynb
"""

import pandas as pd 
data_path = "/content/newdeadlines.csv"

Deadlines=  pd.read_csv(data_path, index_col=0)
(Deadlines)

import pandas as pd
import matplotlib.pyplot as plt

df=pd.DataFrame(Deadlines)

ax=df.plot.bar(rot=0,  
               title='Deadlines from 2020 for future commitments per UK party',
               color=sns.color_palette("Paired"))
ax.set_ylim([2020,2060])
plt.xlabel("UK Party")
plt.ylabel("Years")
plt.title("Deadlines from 2020 for future commitments per UK party")
plt.show()